# I. Exploratory Data Analysis
----------------------------------------
User table ("takehome_users") - data on 12,000 users who signed up for the product in the last two years.

In [168]:
#import packages
import pandas as pd
import numpy as np
from datetime import datetime
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

# Print Users Dataset
users_df = pd.read_csv('takehome_users.csv', engine='python') 
users_df.head(12)

,object_id,creation_time,name,email,creation_source,last_session_creation_time,opted_in_to_mailing_list,enabled_for_marketing_drip,org_id,invited_by_user_id
0,1,4/22/14 3:53,Clausen August,AugustCClausen@yahoo.com,GUEST_INVITE,1.398139e+09,1,0,11,10803.0
1,2,11/15/13 3:45,Poole Matthew,MatthewPoole@gustr.com,ORG_INVITE,1.396238e+09,0,0,1,316.0
2,3,3/19/13 23:14,Bottrill Mitchell,MitchellBottrill@gustr.com,ORG_INVITE,1.363735e+09,0,0,94,1525.0
3,4,5/21/13 8:09,Clausen Nicklas,NicklasSClausen@yahoo.com,GUEST_INVITE,1.369210e+09,0,0,1,5151.0
4,5,1/17/13 10:14,Raw Grace,GraceRaw@yahoo.com,GUEST_INVITE,1.358850e+09,0,0,193,5240.0
5,6,12/17/13 3:37,Cunha Eduardo,EduardoPereiraCunha@yahoo.com,GUEST_INVITE,1.387424e+09,0,0,197,11241.0
6,7,12/16/12 13:24,Sewell Tyler,TylerSewell@jourrapide.com,SIGNUP,1.356010e+09,0,1,37,NaN
7,8,7/31/13 5:34,Hamilton Danielle,DanielleHamilton@yahoo.com,PERSONAL_PROJECTS,NaN,1,1,74,NaN
8,9,11/5/13 4:04,Amsel Paul,PaulAmsel@hotmail.com,PERSONAL_PROJECTS,NaN,0,0,302,NaN
9,10,1/16/13 22:08,Santos Carla,CarlaFerreiraSantos@gustr.com,ORG_INVITE,1.401833e+09,1,1,318,4143.0
10,11,12/26/13 3:55,Paulsen Malthe,MaltheAPaulsen@gustr.com,SIGNUP,1.388117e+09,0,0,69,NaN
11,12,4/17/14 23:48,Mathiesen L�rke,LaerkeLMathiesen@cuvox.de,ORG_INVITE,NaN,0,0,130,9270.0

Usage summary table ("takehome_user_engagement") - row for each day that a user logged into the product.

In [169]:
# Print User Engagement Dataset
engagement_df = pd.read_csv('takehome_user_engagement.csv')
engagement_df.head()

            time_stamp  user_id  visited
0  2014-04-22 03:53:30        1        1
1  2013-11-15 03:45:04        2        1
2  2013-11-29 03:45:04        2        1
3  2013-12-09 03:45:04        2        1
4  2013-12-25 03:45:04        2        1

In [170]:
engagement_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 207917 entries, 0 to 207916
Data columns (total 3 columns):
time_stamp    207917 non-null object
user_id       207917 non-null int64
visited       207917 non-null int64
dtypes: int64(2), object(1)
memory usage: 4.8+ MB

In [171]:
users_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 10 columns):
object_id                     12000 non-null int64
creation_time                 12000 non-null object
name                          12000 non-null object
email                         12000 non-null object
creation_source               12000 non-null object
last_session_creation_time    8823 non-null float64
opted_in_to_mailing_list      12000 non-null int64
enabled_for_marketing_drip    12000 non-null int64
org_id                        12000 non-null int64
invited_by_user_id            6417 non-null float64
dtypes: float64(2), int64(4), object(4)
memory usage: 937.6+ KB

There are no missing values for the engagement dataframe. In the users dataframe, there are 3177 missing values in the column 'last_session_creation_time' and 5583 missing entries in 'invited_by_user_id'.

An "adopted" user has logged into the product on three separate days in at least one seven-day period.

In [172]:
# Convert object to datetime
engagement_df['time_stamp'] = pd.to_datetime(engagement_df['time_stamp'])
# print(engagement_df.info())

# Set index to 'time_stamp'
engagement_df = engagement_df.set_index('time_stamp')
engagement_df

                     user_id  visited
time_stamp
2014-04-22 03:53:30        1        1
2013-11-15 03:45:04        2        1
2013-11-29 03:45:04        2        1
2013-12-09 03:45:04        2        1
2013-12-25 03:45:04        2        1
2013-12-31 03:45:04        2        1
2014-01-08 03:45:04        2        1
2014-02-03 03:45:04        2        1
2014-02-08 03:45:04        2        1
2014-02-09 03:45:04        2        1
2014-02-13 03:45:04        2        1
2014-02-16 03:45:04        2        1
2014-03-09 03:45:04        2        1
2014-03-13 03:45:04        2        1
2014-03-31 03:45:04        2        1
2013-03-19 23:14:52        3        1
2013-05-22 08:09:28        4        1
2013-01-22 10:14:20        5        1
2013-12-19 03:37:06        6        1
2012-12-20 13:24:32        7        1
2013-01-16 22:08:03       10        1
2013-01-22 22:08:03       10        1
2013-01-30 22:08:03       10        1
2013-02-04 22:08:03       10        1
2013-02-06 22:08:03       10        1
2013-02-14 22:08:03       10        1
2013-02-17 22:08:03       10        1
2013-02-19 22:08:03       10        1
2013-02-26 22:08:03       10        1
2013-03-01 22:08:03       10        1
2013-03-02 22:08:03       10        1
2013-03-05 22:08:03       10        1
2013-03-09 22:08:03       10        1
2013-03-15 22:08:03       10        1
2013-03-17 22:08:03       10        1
2013-03-20 22:08:03       10        1
2013-03-22 22:08:03       10        1
2013-03-26 22:08:03       10        1
2013-04-07 22:08:03       10        1
2013-04-11 22:08:03       10        1
2013-04-13 22:08:03       10        1
2013-04-14 22:08:03       10        1
2013-04-17 22:08:03       10        1
2013-04-19 22:08:03       10        1
2013-04-24 22:08:03       10        1
2013-04-26 22:08:03       10        1
2013-04-27 22:08:03       10        1
2013-04-30 22:08:03       10        1
2013-05-01 22:08:03       10        1
2013-05-02 22:08:03       10        1
...                      ...      ...
2013-04-02 01:53:48    11981        1
2013-12-06 14:39:15    11982        1
2013-07-30 00:23:36    11983        1
2014-02-11 21:26:11    11984        1
2012-07-01 01:02:14    11986        1
2013-03-15 03:21:01    11987        1
2014-03-17 11:04:47    11988        1
2014-03-18 11:04:47    11988        1
2014-03-19 11:04:47    11988        1
2014-03-22 11:04:47    11988        1
2014-03-24 11:04:47    11988        1
2014-03-28 11:04:47    11988        1
2014-03-31 11:04:47    11988        1
2014-04-01 11:04:47    11988        1
2014-04-05 11:04:47    11988        1
2014-04-10 11:04:47    11988        1
2014-04-13 11:04:47    11988        1
2014-04-15 11:04:47    11988        1
2014-04-16 11:04:47    11988        1
2014-04-25 11:04:47    11988        1
2014-04-28 11:04:47    11988        1
2014-04-29 11:04:47    11988        1
2014-04-30 11:04:47    11988        1
2014-05-04 11:04:47    11988        1
2014-05-08 11:04:47    11988        1
2014-05-14 11:04:47    11988        1
2014-05-17 11:04:47    11988        1
2014-05-18 11:04:47    11988        1
2014-05-19 11:04:47    11988        1
2014-05-20 11:04:47    11988        1
2014-05-21 11:04:47    11988        1
2014-05-23 11:04:47    11988        1
2014-05-24 11:04:47    11988        1
2014-05-26 11:04:47    11988        1
2014-05-27 11:04:47    11988        1
2014-06-01 11:04:47    11988        1
2013-09-07 11:24:33    11989        1
2013-07-06 21:00:48    11990        1
2014-04-20 14:22:45    11991        1
2014-04-25 14:22:45    11991        1
2014-04-28 14:22:45    11991        1
2014-05-17 14:22:45    11991        1
2014-05-30 14:22:45    11991        1
2014-04-11 19:39:56    11992        1
2013-10-22 13:33:17    11995        1
2013-09-06 06:14:15    11996        1
2013-01-15 18:28:37    11997        1
2014-04-27 12:45:16    11998        1
2012-06-02 11:55:59    11999        1
2014-01-26 08:57:12    12000        1

[207917 rows x 2 columns]

In [173]:
#List unique values in the engagement_df['user_id'] column
unique_users = engagement_df['user_id'].unique()
print(unique_users)

[    1     2     3 ..., 11998 11999 12000]

There are 12,000 unique user id's

In [174]:
#  Select out users in the engagement data who have logged in on three seperate days

# 1) Max and min dates (engagement_df)
# 2) Create 1 week bins
# 3) Loop through dates and select users ('user_id') with 3 or more visits on separate days('visited' ) that falls within a one week range

In [175]:
# Print range of dates of when users were observed
print('min:', engagement_df.index.min())
print('max:', engagement_df.index.max())

min: 2012-05-31 08:20:06
max: 2014-06-06 14:58:50

#### Create new dataframe of users who have logged in on three seperate days in at least one seven-day period:

In [176]:
# Group the datapoints by periods of 1 week and by user_id
adopted_user_df = engagement_df.groupby(['user_id', pd.TimeGrouper(freq='7D')]).sum()

# Filter users that have 3 or more visits in one week period
adopted_user_df = adopted_user_df.loc[adopted_user_df.visited >= 3, :]

# Reset index
adopted_user_df = adopted_user_df.reset_index()

# Print Dataframe
adopted_user_df.head(10)

   user_id          time_stamp  visited
0        2 2014-02-06 08:20:06        3
1       10 2013-02-14 08:20:06        3
2       10 2013-02-28 08:20:06        3
3       10 2013-03-14 08:20:06        3
4       10 2013-04-11 08:20:06        4
5       10 2013-04-25 08:20:06        4
6       10 2013-05-02 08:20:06        5
7       10 2013-05-09 08:20:06        3
8       10 2013-05-23 08:20:06        4
9       10 2013-06-06 08:20:06        4

In [177]:
# Create separate Dataframe for all unique "adopted" users
adoption_df = pd.DataFrame(adopted_user_df['user_id'].unique(), columns={"object_id":"0"})
adoption_df['user_status'] = 'Active'
adoption_df.head()

   object_id user_status
0          2      Active
1         10      Active
2         42      Active
3         43      Active
4         53      Active

In [178]:
# Merge adoption_df and users_df
active_user_df = pd.merge(left=users_df, right=adoption_df, on=None, how='outer')
active_user_df['user_status'] = active_user_df['user_status'].fillna(value='Inactive')
active_user_df

,object_id,creation_time,name,email,creation_source,last_session_creation_time,opted_in_to_mailing_list,enabled_for_marketing_drip,org_id,invited_by_user_id,user_status
0,1,4/22/14 3:53,Clausen August,AugustCClausen@yahoo.com,GUEST_INVITE,1.398139e+09,1,0,11,10803.0,Inactive
1,2,11/15/13 3:45,Poole Matthew,MatthewPoole@gustr.com,ORG_INVITE,1.396238e+09,0,0,1,316.0,Active
2,3,3/19/13 23:14,Bottrill Mitchell,MitchellBottrill@gustr.com,ORG_INVITE,1.363735e+09,0,0,94,1525.0,Inactive
3,4,5/21/13 8:09,Clausen Nicklas,NicklasSClausen@yahoo.com,GUEST_INVITE,1.369210e+09,0,0,1,5151.0,Inactive
4,5,1/17/13 10:14,Raw Grace,GraceRaw@yahoo.com,GUEST_INVITE,1.358850e+09,0,0,193,5240.0,Inactive
5,6,12/17/13 3:37,Cunha Eduardo,EduardoPereiraCunha@yahoo.com,GUEST_INVITE,1.387424e+09,0,0,197,11241.0,Inactive
6,7,12/16/12 13:24,Sewell Tyler,TylerSewell@jourrapide.com,SIGNUP,1.356010e+09,0,1,37,NaN,Inactive
7,8,7/31/13 5:34,Hamilton Danielle,DanielleHamilton@yahoo.com,PERSONAL_PROJECTS,NaN,1,1,74,NaN,Inactive
8,9,11/5/13 4:04,Amsel Paul,PaulAmsel@hotmail.com,PERSONAL_PROJECTS,NaN,0,0,302,NaN,Inactive
9,10,1/16/13 22:08,Santos Carla,CarlaFerreiraSantos@gustr.com,ORG_INVITE,1.401833e+09,1,1,318,4143.0,Active
10,11,12/26/13 3:55,Paulsen Malthe,MaltheAPaulsen@gustr.com,SIGNUP,1.388117e+09,0,0,69,NaN,Inactive
11,12,4/17/14 23:48,Mathiesen L�rke,LaerkeLMathiesen@cuvox.de,ORG_INVITE,NaN,0,0,130,9270.0,Inactive
12,13,3/30/14 16:19,Fry Alexander,AlexanderDFry@cuvox.de,ORG_INVITE,1.396196e+09,0,0,254,11204.0,Inactive
13,14,10/11/12 16:14,Rivera Bret,BretKRivera@gmail.com,SIGNUP,1.350058e+09,0,0,0,NaN,Inactive
14,15,7/16/13 21:33,Theiss Ralf,RalfTheiss@hotmail.com,PERSONAL_PROJECTS,NaN,0,0,175,NaN,Inactive
15,16,2/11/13 10:09,Engel Ren�,ReneEngel@hotmail.com,PERSONAL_PROJECTS,NaN,0,0,211,NaN,Inactive
16,17,4/9/14 14:39,Reynolds Anthony,AnthonyReynolds@jourrapide.com,GUEST_INVITE,1.397314e+09,1,0,175,1600.0,Inactive
17,18,8/24/13 0:26,Gregersen Celina,CelinaAGregersen@jourrapide.com,GUEST_INVITE,NaN,0,0,2,3153.0,Inactive
18,19,5/24/13 14:56,Collins Arlene,ArleneRCollins@gmail.com,SIGNUP,1.369926e+09,1,0,0,NaN,Inactive
19,20,3/6/14 11:46,Helms Mikayla,lqyvjilf@uhzdq.com,SIGNUP,1.401364e+09,0,0,58,NaN,Inactive
20,21,1/22/13 12:27,Hunter Alfie,AlfieHunter@gmail.com,PERSONAL_PROJECTS,1.358858e+09,0,0,54,NaN,Inactive
21,22,2/10/14 6:00,Myers Jordan,JordanMyers@gmail.com,ORG_INVITE,1.392012e+09,0,0,7,2994.0,Inactive
22,23,8/17/12 8:30,Souza Alice,AliceAraujoSouza@gustr.com,ORG_INVITE,1.345279e+09,1,0,6,23.0,Inactive
23,24,9/9/13 22:20,Woodruff James,JamesTWoodruff@cuvox.de,SIGNUP,1.378765e+09,1,0,123,NaN,Inactive
24,25,2/25/14 0:11,Stone Elise,EliseStone@jourrapide.com,GUEST_INVITE,1.393373e+09,1,0,81,6312.0,Inactive
25,26,7/28/13 0:53,Wexler Florian,FlorianWexler@jourrapide.com,ORG_INVITE,NaN,0,0,56,11857.0,Inactive
26,27,1/14/14 17:35,Santos Lu�s,LuisPintoSantos@gmail.com,ORG_INVITE,1.389807e+09,0,0,134,4189.0,Inactive
27,28,2/11/13 20:00,Weissmuller Marko,MarkoWeissmuller@jourrapide.com,SIGNUP,1.360872e+09,0,0,6,NaN,Inactive
28,29,9/16/13 2:08,Fernandes Evelyn,EvelynSousaFernandes@jourrapide.com,SIGNUP,1.379384e+09,0,0,92,NaN,Inactive
29,30,6/4/13 0:44,Egger Leah,LeahEgger@jourrapide.com,GUEST_INVITE,1.370307e+09,0,0,251,4835.0,Inactive
30,31,1/23/14 5:21,Moffitt Lily,LilyMoffitt@jourrapide.com,SIGNUP,1.390541e+09,0,0,283,NaN,Inactive
31,32,4/17/13 16:21,Perez Timothy,TimothyJPerez@yahoo.com,PERSONAL_PROJECTS,NaN,1,1,98,NaN,Inactive
32,33,3/11/14 6:29,Araujo Jos�,JoseMartinsAraujo@cuvox.de,GUEST_INVITE,1.401518e+09,0,0,401,79.0,Inactive
33,34,2/3/14 20:55,Holm Sara,SaraMHolm@hotmail.com,ORG_INVITE,NaN,0,0,33,3721.0,Inactive
34,35,8/1/13 10:55,Krueger Dieter,DieterKrueger@gustr.com,PERSONAL_PROJECTS,NaN,0,0,59,NaN,Inactive
35,36,8/6/13 9:08,Andresen Peter,PeterTAndresen@cuvox.de,GUEST_INVITE,1.375780e+09,1,0,109,6805.0,Inactive
36,37,9/25/12 14:37,Carr-Glyn Ella,EllaCarr-Glyn@yahoo.com,SIGNUP,1.348670e+09,0,0,276,NaN,Inactive
37,38,5/25/14 6:59,Eiffel Marko,MarkoEiffel@gmail.com,PERSONAL_PROJECTS,NaN,0,0,208,NaN,Inactive
38,39,9/10/13 23:09,Winter Finley,FinleyWinter@cuvox.de,ORG_INVITE,NaN,1,0,332,3335.0,Inactive
39,40,5/26/14 10:29,Santiago Shirley,ShirleyJSantiago@gmail.com,GUEST_INVITE,NaN,0,0,2,5377.0,Inactive
40,41,4/30/14 23:38,Herman Christian,ChristianHerman@hotmail.com,ORG_INVITE,1.398901e+09,0,0,64,9286.0,Inactive
41,42,11/11/12 19:05,Pinto Giovanna,GiovannaCunhaPinto@cuvox.de,SIGNUP,1.401045e+09,1,0,235,NaN,Active
42,43,12/31/12 7:13,Gomes Beatrice,vgqmpljq@yyyxt.com,GUEST_INVITE,1.366010e+09,0,0,63,149.0,Active
43,44,5/28/14 16:43,Vogel Jessika,JessikaVogel@jourrapide.com,SIGNUP,1.401382e+09,0,0,14,NaN,Inactive
44,45,4/29/14 21:55,Boxer Gabrielle,GabrielleBoxer@gmail.com,SIGNUP_GOOGLE_AUTH,1.398895e+09,1,0,4,NaN,Inactive
45,46,1/1/14 18:42,Landry Juliet,JulietTLandry@yahoo.com,ORG_INVITE,1.388602e+09,0,0,127,2125.0,Inactive
46,47,6/7/12 13:23,Carrillo Hillary,HillaryJCarrillo@yahoo.com,ORG_INVITE,1.339162e+09,1,1,32,11800.0,Inactive
47,48,11/3/13 14:37,Milton Randal,cawizywo@cslyn.com,ORG_INVITE,1.383576e+09,0,0,224,526.0,Inactive
48,49,10/13/13 10:06,Thompson Terence,TerenceSThompson@hotmail.com,SIGNUP,1.381659e+09,0,0,304,NaN,Inactive
49,50,6/3/12 11:02,Oliveira Gabrielly,GabriellyAlmeidaOliveira@gmail.com,GUEST_INVITE,1.350990e+09,0,0,61,50.0,Inactive
...,...,...,...,...,...,...,...,...,...,...,...
11950,11951,5/24/14 15:28,Silva Marcos,MarcosPintoSilva@gustr.com,ORG_INVITE,1.401032e+09,0,0,17,2314.0,Inactive
11951,11952,1/20/13 0:12,Robb Jasper,JasperRobb@gmail.com,ORG_INVITE,NaN,0,0,1,801.0,Inactive
11952,11953,3/13/13 22:38,Garcia Arturo,ArturoHGarcia@hotmail.com,ORG_INVITE,NaN,0,0,148,6247.0,Inactive
11953,11954,9/27/13 3:53,Brown Linda,LindaRBrown@yahoo.com,ORG_INVITE,NaN,0,0,36,5917.0,Inactive
11954,11955,12/12/13 11:27,Hofmann Anja,AnjaHofmann@gmail.com,PERSONAL_PROJECTS,NaN,0,0,29,NaN,Inactive
11955,11956,8/8/13 11:44,Jepsen Michelle,MichelleJJepsen@gustr.com,PERSONAL_PROJECTS,NaN,0,0,322,NaN,Inactive
11956,11957,2/3/13 15:00,Vaux Mariam,MariamVaux@yahoo.com,SIGNUP,1.400944e+09,0,0,413,NaN,Active
11957,11958,5/25/13 6:28,Leake Taj,TajLeake@gmail.com,SIGNUP,1.400049e+09,1,0,176,NaN,Active
11958,11959,9/24/12 23:34,Walsh Aidan,AidanWalsh@cuvox.de,GUEST_INVITE,1.401666e+09,1,1,105,5093.0,Active
11959,11960,12/16/12 7:36,Cardoso Murilo,MuriloCostaCardoso@yahoo.com,GUEST_INVITE,1.355643e+09,0,0,273,7702.0,Inactive
11960,11961,6/11/13 19:33,Ashby Charli,pvjjpyyz@bikch.com,GUEST_INVITE,1.390419e+09,0,0,2,2562.0,Active
11961,11962,10/27/12 21:36,Dreher Simone,SimoneDreher@gmail.com,ORG_INVITE,1.351460e+09,1,1,21,5781.0,Inactive
11962,11963,5/4/14 17:01,Welch Robert,RobertAWelch@yahoo.com,PERSONAL_PROJECTS,1.400605e+09,1,0,27,NaN,Inactive
11963,11964,2/2/13 15:39,Bibler Thelma,binrwhty@owujh.com,SIGNUP,1.401032e+09,0,0,0,NaN,Active
11964,11965,4/25/14 7:17,Storey Lewis,LewisStorey@cuvox.de,GUEST_INVITE,1.400657e+09,0,0,65,11251.0,Active
11965,11966,1/1/13 2:28,Ferreira Luana,LuanaAzevedoFerreira@gmail.com,PERSONAL_PROJECTS,NaN,0,0,39,NaN,Inactive
11966,11967,1/12/14 8:12,Barbosa Pedro,PedroFernandesBarbosa@gmail.com,GUEST_INVITE,1.401524e+09,0,0,15,5688.0,Active
11967,11968,4/1/13 5:00,Thorsen Marcus,MarcusMThorsen@gmail.com,SIGNUP_GOOGLE_AUTH,1.365224e+09,1,1,273,NaN,Inactive
11968,11969,6/1/13 0:48,Dickinson Aidan,AidanDickinson@hotmail.com,GUEST_INVITE,1.401411e+09,1,1,52,6647.0,Active
11969,11970,10/19/13 9:51,Bartlett Brooke,BrookeBartlett@gmail.com,SIGNUP,NaN,0,0,126,NaN,Inactive
11970,11971,5/4/13 6:54,Ferreira Beatrice,BeatriceBarbosaFerreira@yahoo.com,GUEST_INVITE,NaN,0,0,3,11854.0,Inactive
11971,11972,9/13/12 23:23,Penington Jamie,JamiePenington@yahoo.com,ORG_INVITE,NaN,0,0,16,7012.0,Inactive
11972,11973,10/30/12 3:09,Simmons Thomas,ThomasSimmons@gmail.com,PERSONAL_PROJECTS,NaN,0,0,52,NaN,Inactive
11973,11974,12/26/12 16:42,Scott James,JamesJScott@gmail.com,SIGNUP,1.356713e+09,0,0,167,NaN,Inactive
11974,11975,3/23/13 11:10,Daecher J�rgen,JurgenDaecher@gustr.com,GUEST_INVITE,1.400757e+09,1,0,31,6410.0,Active
11975,11976,12/25/13 22:01,Kohl Leah,LeahKohl@hotmail.com,PERSONAL_PROJECTS,NaN,0,0,248,NaN,Inactive
11976,11977,9/17/13 18:58,Crary Joshua,JoshuaHCrary@gmail.com,SIGNUP_GOOGLE_AUTH,1.379704e+09,0,0,144,NaN,Inactive
11977,11978,4/23/14 16:28,Castro Pedro,PedroCunhaCastro@gustr.com,PERSONAL_PROJECTS,NaN,1,0,29,NaN,Inactive
11978,11979,1/28/13 9:26,Hurst Harley,HarleyHurst@yahoo.com,SIGNUP,1.359624e+09,0,0,2,NaN,Inactive
11979,11980,2/2/14 15:23,Gloeckner Franziska,ljnnbqdr@cgbld.com,ORG_INVITE,1.397835e+09,0,0,406,3068.0,Inactive
11980,11981,3/5/13 1:53,Fry Tyler,TylerFry@gmail.com,GUEST_INVITE,1.364868e+09,0,0,110,5775.0,Inactive
11981,11982,12/6/13 14:39,Barajas Maria,MariaCBarajas@gmail.com,ORG_INVITE,1.386341e+09,1,1,57,2527.0,Inactive
11982,11983,7/30/13 0:23,Engel Mike,MikeEngel@gmail.com,SIGNUP_GOOGLE_AUTH,1.375144e+09,0,0,234,NaN,Inactive
11983,11984,2/11/14 21:26,Reed Cerys,CerysReed@yahoo.com,SIGNUP,1.392154e+09,0,0,170,NaN,Inactive
11984,11985,7/8/13 17:23,Jespersen Marcus,MarcusTJespersen@cuvox.de,PERSONAL_PROJECTS,NaN,0,0,74,NaN,Inactive
11985,11986,6/24/12 1:02,Ribeiro Clara,ClaraBarrosRibeiro@gmail.com,SIGNUP_GOOGLE_AUTH,1.341105e+09,0,0,111,NaN,Inactive
11986,11987,3/15/13 3:21,Reed Poppy,ftdkorrj@uyhoy.com,SIGNUP,1.363318e+09,0,0,1,NaN,Inactive
11987,11988,3/15/14 11:04,Minick John,JohnFMinick@yahoo.com,PERSONAL_PROJECTS,1.401621e+09,0,0,114,NaN,Active
11988,11989,9/2/13 11:24,Pereira Emilly,EmillyOliveiraPereira@gmail.com,SIGNUP_GOOGLE_AUTH,1.378553e+09,1,0,22,NaN,Inactive
11989,11990,7/5/13 21:00,Juhl Aase,AasePJuhl@jourrapide.com,ORG_INVITE,1.373144e+09,0,0,25,3944.0,Inactive
11990,11991,4/20/14 14:22,Vaughn Arthur,ArthurJVaughn@gmail.com,SIGNUP_GOOGLE_AUTH,1.401460e+09,0,0,388,NaN,Inactive
11991,11992,4/9/14 19:39,Hermansen Amanda,AmandaAHermansen@yahoo.com,PERSONAL_PROJECTS,1.397245e+09,0,0,129,NaN,Inactive
11992,11993,3/28/13 23:24,Townsend Isabel,IsabelTownsend@cuvox.de,PERSONAL_PROJECTS,NaN,0,0,281,NaN,Inactive
11993,11994,6/5/12 4:46,Grimstone Joel,conxzghp@eaouk.com,GUEST_INVITE,NaN,0,0,84,5450.0,Inactive
11994,11995,10/21/13 13:33,Werfel Sebastian,SebastianWerfel@gmail.com,PERSONAL_PROJECTS,1.382449e+09,0,0,0,NaN,Inactive
11995,11996,9/6/13 6:14,Meier Sophia,SophiaMeier@gustr.com,ORG_INVITE,1.378448e+09,0,0,89,8263.0,Inactive
11996,11997,1/10/13 18:28,Fisher Amelie,AmelieFisher@gmail.com,SIGNUP_GOOGLE_AUTH,1.358275e+09,0,0,200,NaN,Inactive
11997,11998,4/27/14 12:45,Haynes Jake,JakeHaynes@cuvox.de,GUEST_INVITE,1.398603e+09,1,1,83,8074.0,Inactive
11998,11999,5/31/12 11:55,Faber Annett,mhaerzxp@iuxiw.com,PERSONAL_PROJECTS,1.338638e+09,0,0,6,NaN,Inactive
11999,12000,1/26/14 8:57,Lima Tha�s,ThaisMeloLima@hotmail.com,SIGNUP,1.390727e+09,0,1,0,NaN,Inactive

In [179]:
# Drop name and email column
active_user_df = active_user_df.drop(['creation_time','name', 'email'], axis=1)
print(active_user_df.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 12000 entries, 0 to 11999
Data columns (total 8 columns):
object_id                     12000 non-null int64
creation_source               12000 non-null object
last_session_creation_time    8823 non-null float64
opted_in_to_mailing_list      12000 non-null int64
enabled_for_marketing_drip    12000 non-null int64
org_id                        12000 non-null int64
invited_by_user_id            6417 non-null float64
user_status                   12000 non-null object
dtypes: float64(2), int64(4), object(2)
memory usage: 843.8+ KB
None

In [180]:
#Drop NaNs
active_user_df = active_user_df.dropna()
active_user_df

,object_id,creation_source,last_session_creation_time,opted_in_to_mailing_list,enabled_for_marketing_drip,org_id,invited_by_user_id,user_status
0,1,GUEST_INVITE,1.398139e+09,1,0,11,10803.0,Inactive
1,2,ORG_INVITE,1.396238e+09,0,0,1,316.0,Active
2,3,ORG_INVITE,1.363735e+09,0,0,94,1525.0,Inactive
3,4,GUEST_INVITE,1.369210e+09,0,0,1,5151.0,Inactive
4,5,GUEST_INVITE,1.358850e+09,0,0,193,5240.0,Inactive
5,6,GUEST_INVITE,1.387424e+09,0,0,197,11241.0,Inactive
9,10,ORG_INVITE,1.401833e+09,1,1,318,4143.0,Active
12,13,ORG_INVITE,1.396196e+09,0,0,254,11204.0,Inactive
16,17,GUEST_INVITE,1.397314e+09,1,0,175,1600.0,Inactive
21,22,ORG_INVITE,1.392012e+09,0,0,7,2994.0,Inactive
22,23,ORG_INVITE,1.345279e+09,1,0,6,23.0,Inactive
24,25,GUEST_INVITE,1.393373e+09,1,0,81,6312.0,Inactive
26,27,ORG_INVITE,1.389807e+09,0,0,134,4189.0,Inactive
29,30,GUEST_INVITE,1.370307e+09,0,0,251,4835.0,Inactive
32,33,GUEST_INVITE,1.401518e+09,0,0,401,79.0,Inactive
35,36,GUEST_INVITE,1.375780e+09,1,0,109,6805.0,Inactive
40,41,ORG_INVITE,1.398901e+09,0,0,64,9286.0,Inactive
42,43,GUEST_INVITE,1.366010e+09,0,0,63,149.0,Active
45,46,ORG_INVITE,1.388602e+09,0,0,127,2125.0,Inactive
46,47,ORG_INVITE,1.339162e+09,1,1,32,11800.0,Inactive
47,48,ORG_INVITE,1.383576e+09,0,0,224,526.0,Inactive
49,50,GUEST_INVITE,1.350990e+09,0,0,61,50.0,Inactive
50,51,ORG_INVITE,1.377165e+09,0,1,0,9093.0,Inactive
52,53,GUEST_INVITE,1.367798e+09,0,0,37,3641.0,Active
53,54,GUEST_INVITE,1.363783e+09,1,1,51,3876.0,Inactive
55,56,GUEST_INVITE,1.385974e+09,0,0,229,55.0,Inactive
56,57,GUEST_INVITE,1.384883e+09,0,0,88,2436.0,Inactive
57,58,ORG_INVITE,1.359395e+09,1,0,304,6447.0,Inactive
59,60,ORG_INVITE,1.400195e+09,0,0,88,3463.0,Inactive
65,66,ORG_INVITE,1.391439e+09,0,0,215,11389.0,Inactive
66,67,ORG_INVITE,1.398337e+09,0,0,141,763.0,Inactive
68,69,GUEST_INVITE,1.401445e+09,0,0,107,5022.0,Active
72,73,ORG_INVITE,1.366220e+09,0,0,389,6169.0,Inactive
79,80,ORG_INVITE,1.399239e+09,1,1,49,238.0,Inactive
81,82,GUEST_INVITE,1.401848e+09,0,0,91,3732.0,Active
82,83,ORG_INVITE,1.359280e+09,1,0,172,9016.0,Inactive
83,84,ORG_INVITE,1.390971e+09,0,0,8,2050.0,Inactive
84,85,ORG_INVITE,1.376935e+09,1,1,43,10481.0,Inactive
85,86,ORG_INVITE,1.352861e+09,0,0,249,9312.0,Inactive
89,90,ORG_INVITE,1.375836e+09,0,0,10,5961.0,Inactive
95,96,ORG_INVITE,1.395708e+09,0,0,130,451.0,Inactive
97,98,ORG_INVITE,1.399996e+09,0,0,196,6529.0,Inactive
98,99,ORG_INVITE,1.349048e+09,0,1,335,1261.0,Inactive
99,100,ORG_INVITE,1.371458e+09,0,0,375,8357.0,Inactive
100,101,GUEST_INVITE,1.376693e+09,0,0,303,5141.0,Inactive
102,103,GUEST_INVITE,1.354445e+09,1,1,25,4144.0,Inactive
104,105,ORG_INVITE,1.353854e+09,1,1,134,4189.0,Inactive
109,110,ORG_INVITE,1.383487e+09,0,0,295,6954.0,Inactive
111,112,ORG_INVITE,1.355128e+09,0,0,301,3261.0,Inactive
113,114,GUEST_INVITE,1.401547e+09,0,0,112,10054.0,Inactive
...,...,...,...,...,...,...,...,...
11880,11881,ORG_INVITE,1.391013e+09,0,0,153,11795.0,Inactive
11883,11884,GUEST_INVITE,1.388750e+09,0,0,4,3789.0,Inactive
11888,11889,ORG_INVITE,1.383192e+09,0,0,12,6794.0,Inactive
11892,11893,ORG_INVITE,1.401410e+09,1,1,231,343.0,Inactive
11894,11895,GUEST_INVITE,1.401855e+09,0,0,205,5972.0,Active
11896,11897,ORG_INVITE,1.379932e+09,0,0,45,6966.0,Inactive
11898,11899,ORG_INVITE,1.376744e+09,0,0,136,8575.0,Inactive
11903,11904,GUEST_INVITE,1.360832e+09,1,0,297,7857.0,Inactive
11904,11905,ORG_INVITE,1.359999e+09,0,0,82,10628.0,Inactive
11905,11906,ORG_INVITE,1.401917e+09,0,0,200,190.0,Inactive
11906,11907,GUEST_INVITE,1.399474e+09,1,1,193,470.0,Inactive
11907,11908,ORG_INVITE,1.400986e+09,0,0,261,8610.0,Inactive
11908,11909,ORG_INVITE,1.401033e+09,1,0,273,11960.0,Active
11909,11910,GUEST_INVITE,1.356373e+09,0,0,8,2185.0,Inactive
11910,11911,ORG_INVITE,1.342496e+09,0,0,3,4762.0,Inactive
11914,11915,ORG_INVITE,1.394184e+09,0,0,292,2253.0,Inactive
11919,11920,ORG_INVITE,1.401234e+09,0,0,160,1821.0,Active
11920,11921,GUEST_INVITE,1.366443e+09,1,0,414,4572.0,Inactive
11923,11924,ORG_INVITE,1.401923e+09,0,0,14,7286.0,Active
11924,11925,ORG_INVITE,1.370554e+09,0,0,140,9394.0,Inactive
11926,11927,GUEST_INVITE,1.361350e+09,0,0,158,3515.0,Inactive
11927,11928,GUEST_INVITE,1.379764e+09,0,0,52,11973.0,Inactive
11930,11931,ORG_INVITE,1.346479e+09,0,0,37,3641.0,Inactive
11931,11932,GUEST_INVITE,1.390030e+09,0,0,181,5369.0,Inactive
11932,11933,ORG_INVITE,1.383401e+09,1,1,218,6374.0,Inactive
11933,11934,ORG_INVITE,1.361195e+09,1,1,292,4458.0,Inactive
11934,11935,GUEST_INVITE,1.359528e+09,1,1,22,3288.0,Inactive
11935,11936,GUEST_INVITE,1.401202e+09,1,0,39,11966.0,Inactive
11937,11938,GUEST_INVITE,1.400450e+09,0,0,6,3419.0,Inactive
11939,11940,ORG_INVITE,1.401426e+09,1,0,69,10846.0,Inactive
11942,11943,ORG_INVITE,1.366973e+09,0,0,1,801.0,Inactive
11944,11945,ORG_INVITE,1.392250e+09,0,0,19,6134.0,Inactive
11946,11947,ORG_INVITE,1.400728e+09,1,0,66,9964.0,Inactive
11948,11949,GUEST_INVITE,1.401314e+09,0,0,156,3565.0,Inactive
11949,11950,ORG_INVITE,1.393809e+09,0,0,407,8261.0,Inactive
11950,11951,ORG_INVITE,1.401032e+09,0,0,17,2314.0,Inactive
11958,11959,GUEST_INVITE,1.401666e+09,1,1,105,5093.0,Active
11959,11960,GUEST_INVITE,1.355643e+09,0,0,273,7702.0,Inactive
11960,11961,GUEST_INVITE,1.390419e+09,0,0,2,2562.0,Active
11961,11962,ORG_INVITE,1.351460e+09,1,1,21,5781.0,Inactive
11964,11965,GUEST_INVITE,1.400657e+09,0,0,65,11251.0,Active
11966,11967,GUEST_INVITE,1.401524e+09,0,0,15,5688.0,Active
11968,11969,GUEST_INVITE,1.401411e+09,1,1,52,6647.0,Active
11974,11975,GUEST_INVITE,1.400757e+09,1,0,31,6410.0,Active
11979,11980,ORG_INVITE,1.397835e+09,0,0,406,3068.0,Inactive
11980,11981,GUEST_INVITE,1.364868e+09,0,0,110,5775.0,Inactive
11981,11982,ORG_INVITE,1.386341e+09,1,1,57,2527.0,Inactive
11989,11990,ORG_INVITE,1.373144e+09,0,0,25,3944.0,Inactive
11995,11996,ORG_INVITE,1.378448e+09,0,0,89,8263.0,Inactive
11997,11998,GUEST_INVITE,1.398603e+09,1,1,83,8074.0,Inactive

## II. Predictive Modeling
-----------------
Identify which factors predict future user adoption.

### Logistic Regression:

1) Creating Dummy Variables for Feature Selection

In [181]:
# Dummify all columns with categorical features 
dummy_cols_convert = pd.get_dummies(active_user_df, drop_first=True)
dummy_cols_convert

,object_id,last_session_creation_time,opted_in_to_mailing_list,enabled_for_marketing_drip,org_id,invited_by_user_id,creation_source_ORG_INVITE,user_status_Inactive
0,1,1.398139e+09,1,0,11,10803.0,0,1
1,2,1.396238e+09,0,0,1,316.0,1,0
2,3,1.363735e+09,0,0,94,1525.0,1,1
3,4,1.369210e+09,0,0,1,5151.0,0,1
4,5,1.358850e+09,0,0,193,5240.0,0,1
5,6,1.387424e+09,0,0,197,11241.0,0,1
9,10,1.401833e+09,1,1,318,4143.0,1,0
12,13,1.396196e+09,0,0,254,11204.0,1,1
16,17,1.397314e+09,1,0,175,1600.0,0,1
21,22,1.392012e+09,0,0,7,2994.0,1,1
22,23,1.345279e+09,1,0,6,23.0,1,1
24,25,1.393373e+09,1,0,81,6312.0,0,1
26,27,1.389807e+09,0,0,134,4189.0,1,1
29,30,1.370307e+09,0,0,251,4835.0,0,1
32,33,1.401518e+09,0,0,401,79.0,0,1
35,36,1.375780e+09,1,0,109,6805.0,0,1
40,41,1.398901e+09,0,0,64,9286.0,1,1
42,43,1.366010e+09,0,0,63,149.0,0,0
45,46,1.388602e+09,0,0,127,2125.0,1,1
46,47,1.339162e+09,1,1,32,11800.0,1,1
47,48,1.383576e+09,0,0,224,526.0,1,1
49,50,1.350990e+09,0,0,61,50.0,0,1
50,51,1.377165e+09,0,1,0,9093.0,1,1
52,53,1.367798e+09,0,0,37,3641.0,0,0
53,54,1.363783e+09,1,1,51,3876.0,0,1
55,56,1.385974e+09,0,0,229,55.0,0,1
56,57,1.384883e+09,0,0,88,2436.0,0,1
57,58,1.359395e+09,1,0,304,6447.0,1,1
59,60,1.400195e+09,0,0,88,3463.0,1,1
65,66,1.391439e+09,0,0,215,11389.0,1,1
66,67,1.398337e+09,0,0,141,763.0,1,1
68,69,1.401445e+09,0,0,107,5022.0,0,0
72,73,1.366220e+09,0,0,389,6169.0,1,1
79,80,1.399239e+09,1,1,49,238.0,1,1
81,82,1.401848e+09,0,0,91,3732.0,0,0
82,83,1.359280e+09,1,0,172,9016.0,1,1
83,84,1.390971e+09,0,0,8,2050.0,1,1
84,85,1.376935e+09,1,1,43,10481.0,1,1
85,86,1.352861e+09,0,0,249,9312.0,1,1
89,90,1.375836e+09,0,0,10,5961.0,1,1
95,96,1.395708e+09,0,0,130,451.0,1,1
97,98,1.399996e+09,0,0,196,6529.0,1,1
98,99,1.349048e+09,0,1,335,1261.0,1,1
99,100,1.371458e+09,0,0,375,8357.0,1,1
100,101,1.376693e+09,0,0,303,5141.0,0,1
102,103,1.354445e+09,1,1,25,4144.0,0,1
104,105,1.353854e+09,1,1,134,4189.0,1,1
109,110,1.383487e+09,0,0,295,6954.0,1,1
111,112,1.355128e+09,0,0,301,3261.0,1,1
113,114,1.401547e+09,0,0,112,10054.0,0,1
...,...,...,...,...,...,...,...,...
11880,11881,1.391013e+09,0,0,153,11795.0,1,1
11883,11884,1.388750e+09,0,0,4,3789.0,0,1
11888,11889,1.383192e+09,0,0,12,6794.0,1,1
11892,11893,1.401410e+09,1,1,231,343.0,1,1
11894,11895,1.401855e+09,0,0,205,5972.0,0,0
11896,11897,1.379932e+09,0,0,45,6966.0,1,1
11898,11899,1.376744e+09,0,0,136,8575.0,1,1
11903,11904,1.360832e+09,1,0,297,7857.0,0,1
11904,11905,1.359999e+09,0,0,82,10628.0,1,1
11905,11906,1.401917e+09,0,0,200,190.0,1,1
11906,11907,1.399474e+09,1,1,193,470.0,0,1
11907,11908,1.400986e+09,0,0,261,8610.0,1,1
11908,11909,1.401033e+09,1,0,273,11960.0,1,0
11909,11910,1.356373e+09,0,0,8,2185.0,0,1
11910,11911,1.342496e+09,0,0,3,4762.0,1,1
11914,11915,1.394184e+09,0,0,292,2253.0,1,1
11919,11920,1.401234e+09,0,0,160,1821.0,1,0
11920,11921,1.366443e+09,1,0,414,4572.0,0,1
11923,11924,1.401923e+09,0,0,14,7286.0,1,0
11924,11925,1.370554e+09,0,0,140,9394.0,1,1
11926,11927,1.361350e+09,0,0,158,3515.0,0,1
11927,11928,1.379764e+09,0,0,52,11973.0,0,1
11930,11931,1.346479e+09,0,0,37,3641.0,1,1
11931,11932,1.390030e+09,0,0,181,5369.0,0,1
11932,11933,1.383401e+09,1,1,218,6374.0,1,1
11933,11934,1.361195e+09,1,1,292,4458.0,1,1
11934,11935,1.359528e+09,1,1,22,3288.0,0,1
11935,11936,1.401202e+09,1,0,39,11966.0,0,1
11937,11938,1.400450e+09,0,0,6,3419.0,0,1
11939,11940,1.401426e+09,1,0,69,10846.0,1,1
11942,11943,1.366973e+09,0,0,1,801.0,1,1
11944,11945,1.392250e+09,0,0,19,6134.0,1,1
11946,11947,1.400728e+09,1,0,66,9964.0,1,1
11948,11949,1.401314e+09,0,0,156,3565.0,0,1
11949,11950,1.393809e+09,0,0,407,8261.0,1,1
11950,11951,1.401032e+09,0,0,17,2314.0,1,1
11958,11959,1.401666e+09,1,1,105,5093.0,0,0
11959,11960,1.355643e+09,0,0,273,7702.0,0,1
11960,11961,1.390419e+09,0,0,2,2562.0,0,0
11961,11962,1.351460e+09,1,1,21,5781.0,1,1
11964,11965,1.400657e+09,0,0,65,11251.0,0,0
11966,11967,1.401524e+09,0,0,15,5688.0,0,0
11968,11969,1.401411e+09,1,1,52,6647.0,0,0
11974,11975,1.400757e+09,1,0,31,6410.0,0,0
11979,11980,1.397835e+09,0,0,406,3068.0,1,1
11980,11981,1.364868e+09,0,0,110,5775.0,0,1
11981,11982,1.386341e+09,1,1,57,2527.0,1,1
11989,11990,1.373144e+09,0,0,25,3944.0,1,1
11995,11996,1.378448e+09,0,0,89,8263.0,1,1
11997,11998,1.398603e+09,1,1,83,8074.0,0,1

2) Feature Selection using Dummy Variables

In [182]:
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import RFE

# Instantiate a Logistic Regression Classifier (logreg)
logreg = LogisticRegression()

# Choose X = feature and Y = target
Y = dummy_cols_convert['user_status_Inactive']
X_all = dummy_cols_convert.drop('user_status_Inactive', axis=1)

# RFE to help find most important features
rfe = RFE(logreg, 3)
rfe = rfe.fit(X_all, Y)
print(rfe.support_) # support returns boolean with top 3 features
print(rfe.ranking_) # ranking returns an integer with 1 being a top feature

# Get column names (features) from DataFrame, dummy_cols_convert
col_names = X_all.columns.values

# Print best feature names
best_features_raw = rfe.support_ * col_names

# Create list with best feature names
best_features = []

for best_feature in best_features_raw:
    if len(best_feature) > 0:
        best_features.append(best_feature)
        
print('Best Predictors for User Adoption: {}'.format(best_features))

[ True  True False False False  True False]
[1 1 4 5 2 1 3]
Best Predictors for User Adoption: ['object_id', 'last_session_creation_time', 'invited_by_user_id']

## III.  Conclusion
------------------------
- 1439 out of the 12,000 users who signed up in the last two years remained adopted users. An adopted user is defined as a user who has logged into the product on three seperate days in at least one seven-day period.
- Using the Recursive Feature Elimination method, the best features to predict future user adoption are: 

    1) User's id
    
    2) Last login time by user
    
    3) Which user invited them to join

## IV. Recommendations
------------------------
Collect other user information such as gender, age, and location